import cateImg1 from "../src/images/categories/laura-chouette-oWozyqpu1qM-unsplash.jpg";
import cateImg2 from "../src/images/categories/Rectangle 12.jpg";
import cateImg3 from "../src/images/categories/irene-kredenets-dwKiHoqqxk8-unsplash.jpg";
import product1 from "../src/images/products/product1.png";
import product2 from "../src/images/products/product2.png";
import product3 from "../src/images/products/product3.png";
import product4 from "../src/images/products/product4.png";
import product5 from "../src/images/products/product5.png";
import product6 from "../src/images/products/product6.png";
import product7 from "../src/images/products/product7.png";
import sliderImg1 from "../src/images/products/slider1.png";
import sliderImg2 from "../src/images/products/slider2.png";
import sliderImg3 from "../src/images/products/slider3.png";
import sliderImg4 from "../src/images/products/slider4.png";
import sliderImg5 from "../src/images/products/slider5.png";
import productImg1 from "../src/images/product detials/one.png";
import productImg2 from "../src/images/product detials/two.png";
import productImg3 from "../src/images/product detials/three.png";
import productImg4 from "../src/images/product detials/four.png";
import popularImg1 from "../src/images/products/Mask group.png";
import popularImg2 from "../src/images/products/Mask group (1).png";
import cartImg1 from "../src/images/products/image 13cart1.png";
import cartImg2 from "../src/images/products/product-4cart2.png";
import cartImg3 from "../src/images/products/product-2cart3.png";
import reviewImg from "../src/images/reviwe/Ellipse 68.png";
import productImgOne from "../src/images/products/productimgone.png";
import productImgTwo from "../src/images/products/productimgtwo.png";
import productImgThree from "../src/images/products/productimgthree.png";
import cardBg1 from "../src/images/bgone.png";
import cardBg2 from "../src/images/bgtwo.png";
import cardBg3 from "../src/images/bgthree.png";
export const categories = [
  {
    id: 1,
    img: cateImg1,
  },
  {
    id: 2,
    img: cateImg2,
    title: "SLEEP WEAR",
  },
  {
    id: 3,
    img: cateImg3,
    title: "LIGHT JACKETS",
  },
];

export const Products = [
  {
    id: 1,
    img: product1,
    category: "Category",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
  },
  {
    id: 2,
    img: product2,
    category: "Category",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
  },
  {
    id: 3,
    img: product3,
    category: "Category",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
  },
  {
    id: 4,
    img: product4,
    category: "Category",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
  },
];
export const ProductsForCategories = [
  {
    id: 1,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 2,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 3,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 4,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 5,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 6,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 7,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 8,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 9,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 10,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 11,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 12,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 13,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 14,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 15,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 16,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 17,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 18,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 19,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 20,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 21,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 22,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 23,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 24,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  // new
  {
    id: 25,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 26,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 27,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 28,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 29,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 30,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 31,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 32,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 33,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 34,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 35,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 36,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 37,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 38,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 39,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 40,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 41,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 42,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 43,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 44,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 45,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 46,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 47,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 48,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 49,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 50,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 51,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 52,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 53,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 54,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 55,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 56,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 57,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 58,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 59,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 60,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 61,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 62,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 63,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 64,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 65,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 66,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 67,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 68,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 69,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 70,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 71,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 72,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  // new
  {
    id: 73,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 74,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 75,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 76,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 77,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 78,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 79,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 80,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 81,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 82,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 83,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 84,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 85,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 86,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 87,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 88,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 89,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 90,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 91,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 92,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 93,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 94,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 95,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 96,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 97,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 98,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 99,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 100,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 101,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 102,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 103,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 104,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 105,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 106,
    img: product1,
    category: "Bags & shoses",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#F1A002",
    size: "S",
  },
  {
    id: 107,
    img: product2,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 108,
    img: product3,
    category: "Electronics",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#59666F",
    size: "L",
  },
  {
    id: 109,
    img: product4,
    category: "Accessiores",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "XL",
  },
  {
    id: 110,
    img: product5,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XXL",
  },
  {
    id: 111,
    img: product6,
    category: "Bags",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#513532",
    size: "S",
  },
  {
    id: 112,
    img: product7,
    category: "Women’s clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#F1A002",
    size: "M",
  },
  {
    id: 113,
    img: product5,
    category: "Mens clothes",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    colors: "#76EAD7",
    size: "L",
  },
  {
    id: 114,
    img: product7,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#76EAD7",
    size: "XL",
  },
  {
    id: 115,
    img: product5,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "XL",
  },
  {
    id: 116,
    img: product6,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "",
    color: "#59666F",
    size: "S",
  },
  {
    id: 117,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 118,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 119,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
  {
    id: 120,
    img: product2,
    category: "Music",
    name: "Product Name",
    beforePrice: "97.00",
    price: "56.00",
    sale: "Sale",
    color: "#513532",
    size: "M",
  },
];

export const ourCategories = [
  {
    id: 1,
    img: sliderImg1,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 2,
    img: sliderImg2,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 3,
    img: sliderImg3,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 4,
    img: sliderImg4,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 5,
    img: sliderImg5,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 6,
    img: sliderImg3,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 7,
    img: sliderImg4,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
  {
    id: 8,
    img: sliderImg5,
    categoryName: "Category Name",
    numberOfProducts: "20 Product",
  },
];

export const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 1024 },
    items: 5,
  },
  desktop: {
    breakpoint: { max: 1024, min: 800 },
    items: 3,
  },
  tablet: {
    breakpoint: { max: 800, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};
export const responsive2 = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 1024 },
    items: 4,
  },
  desktop: {
    breakpoint: { max: 1024, min: 800 },
    items: 4,
  },
  tablet: {
    breakpoint: { max: 800, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};
export const testimonialData = [
  {
    id: 1,
    reviewerName: "sara saad",
    rating: 4,
    reviewerPic: reviewImg,
    desc: ` We really care about you and your website as much as you
    do.Porto or any other We really care about you and your
    website as much as you do.Porto or any other We really care
    about you and your website as much as you do.Porto or any
    other`,
  },
  {
    id: 2,
    reviewerName: "sara saad",
    rating: 4,
    reviewerPic: reviewImg,
    desc: ` We really care about you and your website as much as you
    do.Porto or any other We really care about you and your
    website as much as you do.Porto or any other We really care
    about you and your website as much as you do.Porto or any
    other`,
  },
  {
    id: 3,
    reviewerName: "sara saad",
    rating: 4,
    reviewerPic: reviewImg,
    desc: ` We really care about you and your website as much as you
    do.Porto or any other We really care about you and your
    website as much as you do.Porto or any other We really care
    about you and your website as much as you do.Porto or any
    other`,
  },
];
export const productDetials = {
  name: "Product Name details",
  rating: 4,
  numberReview: 8,
  priceBeforeDiscount: "89.00",
  priceAfterDiscount: "56.00",
  stock: 100,
  description: `
  It is a long established fact that a reader will be using Lorem Ipsu
distracted by the readable content of a page when  t that a reader 
looking at its layout. The point of using Lorem Ipsum look like rea
is that it has a more-or-less normal distribution of letters look like 
as opposed to using 'Content here, content here', making it look la
look like readable English.
  `,
  productCode: 5889578,
  category: "shose",
  tags: "shose , clothes, mens, fashion, black",
};

export const productDetailsImgs = [
  { img: productImg1 },
  { img: productImg2 },
  { img: productImg3 },
  { img: productImg4 },
];
export const popularProducts = [
  { img: popularImg1 },
  { img: popularImg2 },
  { img: popularImg1 },
  { img: popularImg2 },
  { img: popularImg1 },
  { img: popularImg2 },
];
export const Colors = [
  { color: "#F1A002" },
  { color: "#59666F" },
  { color: "#513532" },
  { color: "#76EAD7" },
];

export const Sizes = [
  { size: "S" },
  { size: "M" },
  { size: "L" },
  { size: "XL" },
  { size: "XXL" },
];
export const CartProducts = [
  {
    id: 1,
    img: cartImg1,
    category: "shose",
    name: "Product Name",
    price: "17.00",
    sale: "Sale",
    color: "#F1A002",
    size: "42 EE",
    stock: 100,
    availableInStock: "In Stock",
    productCode: 5889578,
    qty: 1,
  },
  {
    id: 2,
    img: cartImg2,
    category: "shose",
    name: "Product Name",

    price: "17.00",
    sale: "Sale",
    color: "#F1A002",
    size: "42 EE",
    stock: 100,
    availableInStock: "In Stock",
    productCode: 5889578,
    qty: 1,
  },
  {
    id: 3,
    img: cartImg3,
    category: "shose",
    name: "Product Name",

    price: "17.00",
    sale: "Sale",
    color: "#F1A002",
    size: "42 EE",
    stock: 100,
    availableInStock: "In Stock",
    productCode: 5889578,
    qty: 1,
  },
];

export const myOrdersProducts = [
  {
    id: 1,
    img: productImgOne,
    name: "Product Name",
    desc: "It is a long  fact that a reader will be using lo Ipsudistracted by the readable content ",
    orderDate: "23 sep 2022",
    orderSummary: "3 items",
    status: "Delivered",
    amountTotal: 152,
    img2: productImgTwo,
    name2: "Product Name",
    desc2:
      "It is a long  fact that a reader will be using lo Ipsudistracted by the readable content ",
    img3: productImgThree,
    name3: "Product Name",
    desc3:
      "It is a long  fact that a reader will be using lo Ipsudistracted by the readable content ",
  },
  {
    id: 2,
    img: productImgOne,
    name: "Product Name",
    desc: "It is a long  fact that a reader will be using lo Ipsudistracted by the readable content ",
    orderDate: "23 sep 2022",
    orderSummary: "3 items",
    status: "Delivered",
    amountTotal: 152,
  },
  {
    id: 3,
    img: productImgOne,
    name: "Product Name",
    desc: "It is a long  fact that a reader will be using lo Ipsudistracted by the readable content ",
    orderDate: "23 sep 2022",
    orderSummary: "3 items",
    status: "Delivered",
    amountTotal: 152,
  },
];

export const MyAddresses = [
  {
    id: 1,

    title: "Home address",
    buyer: "buyer name",
    country: "Country name",
    city: "City name",
    street: "Street name",
  },
  {
    id: 2,

    title: "Home address",
    buyer: "buyer name",
    country: "Country name",
    city: "City name",
    street: "Street name",
  },
  {
    id: 3,

    title: "Home address",
    buyer: "buyer name",
    country: "Country name",
    city: "City name",
    street: "Street name",
  },
];

export const CardsPayment = [
  {
    id: 1,
    bgImg: cardBg1,
    card_number: ".... .... .... .289",
    card_holder: "Nice Robin",
    date: "09/25",
  },
  {
    id: 2,
    bgImg: cardBg2,
    card_number: ".... .... .... .289",
    card_holder: "Roronoa Zoro",
    date: "09/25",
  },
  {
    id: 3,
    bgImg: cardBg3,
    card_number: ".... .... .... .289",
    card_holder: "Nice Robin",
    date: "09/25",
  },
];
